"""DataBase creation

Revision ID: 744a0c3b5fb4
Revises: 
Create Date: 2024-10-01 10:13:34.822777

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "744a0c3b5fb4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kittens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column(
            "breed",
            sa.Enum(
                "ABYSSINIAN",
                "BENGAL",
                "BRITISH_SHORTHAIR",
                "MAINE_COON",
                "PERSIAN",
                "RAGDOLL",
                "SIAMESE",
                "SPHYNX",
                "SCOTTISH_FOLD",
                "BURMESE",
                "ORIENTAL_SHORTHAIR",
                "NORMANDY",
                "AMERICAN_SHORTHAIR",
                "SOMALI",
                "DEVON_REX",
                name="breed",
            ),
            nullable=False,
        ),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column(
            "color",
            sa.Enum(
                "BLACK",
                "WHITE",
                "GRAY",
                "ORANGE",
                "CALICO",
                "TABBY",
                "BROWN",
                "CREAM",
                "BLUE",
                "RED",
                "CHOCOLATE",
                "LILAC",
                "TORTIE",
                name="color",
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kittens")
    # ### end Alembic commands ###
